config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :carts, except: [:index, :destroy] do
    collection do
      get :print_receipt
    end
  end

  root :to => "carts#new"
  match '*path' => redirect('/'), via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :items

  validates_presence_of :currency_type
  validates_presence_of :items

  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

  enum currency_type: [:EUR, :USD, :INR]

  FIXERACCESSKEY = 'df3db89847c9cddc94ebe14a2e75d1df'

  def sales_tax
    sales_tax = 0.0
    items.map do |item|
      sales_tax+=item.sales_tax
    end
    sales_tax
  end

  def total_cost
    total_cost = 0.0
    items.map do |item|
      total_cost+=item.price_with_tax
    end
    total_cost
  end   

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :cart, optional: true

  validates_presence_of :quantity, :description, :price

  TAXTYPES = {
      NA: 0,
      BASIC: 0.10,
      IMPORTED: 0.05,
      BOTH: 0.15
    }

    def price_with_tax
      round_of_tax(sales_tax + quantity_price.to_f)
    end

    def sales_tax
      round_of_tax(tax_type * quantity_price.to_f)
    end

    def quantity_price
      quantity.to_f * price.to_f
    end

    def imported?
      description =~ /imported/i
    end

    def exempted?
      return false if description.blank?
      ['book','chocolate','pills'].any? { |word| description.include?(word) }
    end

    def tax_type
      if imported? && !exempted?
        TAXTYPES[:BOTH]
      elsif imported? && exempted?
        TAXTYPES[:IMPORTED]
      elsif !imported? && !exempted?
        TAXTYPES[:BASIC]
      else
        TAXTYPES[:NA]
      end
    end

    private

    def round_of_tax(tax)
      ((tax*100).round/100.0)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
require 'uri'
require 'net/http'

class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :update]

  def new
    @cart = Cart.new
    5.times { @cart.items.build }
  end
  
  def create
    @cart = Cart.new(cart_params)
    @cart.currency_type = "EUR"
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
      else
        5.times { @cart.items.build } if @cart.items.blank?
        format.html { render :new }
      end
    end
  end

  def show
    fetch_fixer_latest
    respond_to do |format|
      format.html
      format.text do
        response.headers['Content-Type'] = 'text/plain'
        response.headers['Content-Disposition'] = "attachment; filename=receipt.txt"
      end
    end
  end

  def update
    @cart.update_attributes(currency_type: params[:currency_type])
    fetch_fixer_latest
  end

  def fetch_fixer_latest
    uri = URI("http://data.fixer.io/api/latest?access_key=#{Cart::FIXERACCESSKEY}&symbols=EUR,INR,USD")
    res = Net::HTTP.get_response(uri)
    response = JSON.parse(res.body) if res.is_a?(Net::HTTPSuccess)
    @currency_conversion_rate = response["rates"].present? && response["rates"][@cart.currency_type].present? ? response["rates"][@cart.currency_type] : 1
  end

  private

  def cart_params
    params.require(:cart).permit(:currency_type, items_attributes: [:quantity, :description, :price])
  end

  def set_cart
    @cart = Cart.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
        success: "alert-success",
        error: "alert-error",
        alert: "alert-danger",
        notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def bootstrap_glyphs_icon(flash_type)
    {
        success: "glyphicon-ok",
        error: "glyphicon-exclamation-sign",
        alert: "glyphicon-warning-sign",
        notice: "glyphicon-info-sign"
    }[flash_type.to_sym] || 'glyphicon-screenshot'
  end

  def currency_conversion(amount, currency_rate)
    (amount * currency_rate).to_f
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/carts/_cart_items.html.erb
<% @cart.try(:items).each do |item| %>
  <tr>
    <td class="center"><%= item.quantity %></td>
    <td class="left"><%= item.description %></td>
    <td class="right" width="16%">
      <% item_price = currency_conversion(item.quantity_price, @currency_conversion_rate) %>
      <%= @cart.currency_type%> <%= number_with_precision(item_price, precision: 2) %>
    </td>
  </tr>
<% end %>

app/views/carts/_cart_total.html.erb
<table class="table table-clear">
  <tbody>
    <tr>
      <td class="left">
        <strong>Total Tax</strong>
      </td>
      <td class="right" id="sales_tax">
        <% sales_tax = @currency_conversion_rate.present? ? @currency_conversion_rate * @cart.sales_tax : @cart.sales_tax %>
        <%= @cart.currency_type%> <%= number_with_precision(sales_tax, precision: 2) %>
      </td>
    </tr>
    <tr>
      <td class="left">
        <strong>Total</strong>
      </td>
      <td class="right" id="total_cost">
        <% total_cost = @currency_conversion_rate.present? ? @currency_conversion_rate * @cart.total_cost : @cart.total_cost %>
        <%= @cart.currency_type%> <%= number_with_precision(total_cost, precision: 2) %>
      </td>
    </tr>
  </tbody>
</table>

app/views/carts/new.html.erb
<div class="container">
  <%= form_for @cart, class: "form-horizontal" do |f| %>
    <%= render "shared/error_messages", :target => @cart %>
    <h2>Item Details</h2>
    <div class="form-group row">
      <label class="control-label col-sm-2">Qty</label>
      <label class="control-label col-sm-4">Item Description</label>
      <label class="control-label col-sm-4">Shelf Price</label>
    </div>
    <%= f.fields_for :items do |item| %>
      <div class="form-group row">
        <div class="col-md-2">
          <%= item.number_field :quantity, class: "form-control" %>
        </div>
        <div class="col-md-4">
          <%= item.text_field :description, class: "form-control", placeholder: "Description" %>
        </div>
        <div class="col-md-4">
          <%= item.number_field :price, value: item.object.price.present? && item.object.price > 0 ? item.object.price : nil, step: 0.01, class: "form-control", placeholder: "EUR" %>
        </div>
      </div>
    <% end %>

    <%= f.submit "Generate Receipt", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/carts/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <strong>Receipt</strong>
      <%= link_to "Download", "/carts/#{@cart.id}.txt" %>
    </div>
    <div class="card-body" id="sales_receipt">
      <div class="table-responsive-sm">
        <table class="table table-borderless">
          <thead>
            <tr>
              <th class="center">Qty</th>
              <th>Item Description</th>
              <th class="right">Price 
                <span>
                  <%= form_tag(cart_path, method: :put, :class => 'form-horizontal', id: 'cart_select') do %>
                    <%= select_tag "currency_type", options_for_select([['EUR', 'EUR'], ['INR', 'INR'], ['USD', 'USD']], @cart.currency_type) %>
                  <% end %>
                </span>
              </th>
            </tr>
          </thead>
          <tbody id="cart_items">
            <%= render partial: "cart_items" %>
          </tbody>
        </table>
      </div>
      <div class="row">
        <div class="col-lg-4 col-sm-5">
        </div>
        <div class="col-lg-4 col-sm-5 ml-auto" id="cart_total">
          <%= render partial: "cart_total" %>
        </div>
      </div>
      <div>
        <%= link_to 'back', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/carts/show.text.erb
Currency: <%= @cart.currency_type %>
Qty Item Description Price
<% @cart.try(:items).each do |item| %>
<%= item.quantity %> <%= item.description %><% item_price = currency_conversion(item.quantity_price, @currency_conversion_rate) %> <%= @cart.currency_type %> <%= number_with_precision(item_price, precision: 2) %>
<% end %>
Total Tax: <% sales_tax = currency_conversion(@cart.sales_tax, @currency_conversion_rate) -%> <%= @cart.currency_type %> <%= number_with_precision(sales_tax, precision: 2) %>
Total: <% total_cost = currency_conversion(@cart.total_cost, @currency_conversion_rate) -%> <%= @cart.currency_type %> <%= number_with_precision(total_cost, precision: 2) %>

app/views/carts/update.js.erb
<% if @cart.errors.blank? %>
  $("#cart_items").html("<%= escape_javascript(render :partial => "cart_items") %>")
  $("#cart_total").html("<%= escape_javascript(render :partial => "cart_total") %>")
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesTax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render partial: 'shared/topbar' %>
      <%= render partial: 'shared/flash' unless flash.empty? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade show in" role='alert'>
    <button class="close" data-dismiss="alert">×</button>
    <span class="glyphicon <%= bootstrap_glyphs_icon(type)%>" aria-hidden="true"></span>
    <span class="sr-only"><%= type.capitalize%>:</span>
    <%= message %>
  </div>
<% end %>

app/views/shared/_topbar.html.erb
<h4 class="text-center">Sales Tax Calculator</h4>
<hr/>